version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - env
      - ant -f test.xml -v
  build:
    commands:
      - ant -f build.xml -v
      - ls dist/*

artifacts:
  files:
    - dist/rectangle.jar
  name: myApp.jar-$(date +%Y-%m-%d)
