version: 0.2
env:
  variables:
    BUILD_NUMBER: $(date +%y%m%d%H%M%S)
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - env
      - ant -f test.xml -v
  build:
    commands:
      - ant -f build.xml -v
      - ls dist/*

artifacts:
  files:
    - dist/rectangle.jar
  name: rectangle-$Env:BUILD_NUMBER.jar
