version: 0.2
env:
  variables:
    BUILD_NUMBER: $(date +%y%m%d%H%M%S)
phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - env
      - ant -f test.xml -v
  build:
    commands:
      - ant -f build.xml -v

artifacts:
  files:
    - dist/rectangle.jar
  name: rectangle-$(BUILD_NUMBER).jar
